raw_log_path = "server.log"
filtered_log_path = "output/filtered.log"
#player_activity_log = "output/player.log"


# [blacklist]


# [format_element]
#     [format_element.chat]
#     start_indicator = "<"
#     end_indicator = ">"

# [format_type]
#     [format_type.chat]
#     filters = ["<", ">"]
#     structure = ["format_element.username", "format_element.remaining_content"]

#     [format_type.login]
#     filters = ["logged in with entity id"]

#     [format_type.logout]
#     filters = ["lost connection"]

#     [format_type.try_command]
#     filters = ["tried command"]

#     [format_type.command]
#     filters = ["issued server command"]
