date_range = [0, 10] # inclusive - exclusive
time_range = [11, 19] # inclusive - exclusive
content_start_char_pos = 20

[files]
raw_log_path = "server.log"
output_directory = "output"

[blacklist]
blacklist = []
auto_blacklist = false
auto_blacklist_percentage = 10
auto_blacklist_passes = 3



# [format_element]
#     [format_element.chat]
#     start_indicator = "<"
#     end_indicator = ">"

# [format_type]
#     [format_type.chat]
#     filters = ["<", ">"]
#     structure = ["format_element.username", "format_element.remaining_content"]

#     [format_type.login]
#     filters = ["logged in with entity id"]

#     [format_type.logout]
#     filters = ["lost connection"]

#     [format_type.try_command]
#     filters = ["tried command"]

#     [format_type.command]
#     filters = ["issued server command"]
